### ISSUE TITLE
Using found_in property with "take all" results in Programming Error using Glulx

### ISSUE THREAD

**Issue by duely** [DavidGriffith/inform6lib#6] opened 2014-09-02 01:07 UTC
The precise error message is: "triet to test "in" or "notin" of <illegal object number 1>".

Example code to reproduce this, compiling with the -G flag:

```inform
Constant Story "Test";
Constant Headline "^An attempt to test!^";

Include "Parser";
Include "VerbLib";

Object Test_Room "test room",
    with
        description     "This room is just a simple test. You can't do anything, nor go anywhere.",
    has
        light
;

Object Test_Object "a nothing",
    with
        name            'nothing',
        description     "Made of nothing, tastes like nothing.",
        found_in        Test_Room,
    has
        scenery
;

[ Initialise;
    location = Test_Room;
];

Include "Grammar";
```

Modifying the found_in attribute of Test_Object results in the error message occurring as soon as the game starts.

**Comment by DavidGriffith** [comment] 2015-01-04 10:41
I can't reproduce this bug, so I'm closing it.

**Closed by DavidGriffith** 2015-01-04 10:41 UTC
